// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBku4N55knjPgqlm2Pf20KdM-7AXOizv8o',
    appId: '1:1015379365622:web:9cf31b18075f607f1de6d7',
    messagingSenderId: '1015379365622',
    projectId: 'womensafety-79a11',
    authDomain: 'womensafety-79a11.firebaseapp.com',
    storageBucket: 'womensafety-79a11.firebasestorage.app',
    measurementId: 'G-JFGWVQ87S6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqTyaVLfRAzvHrp2esyecNAOue5UH60mE',
    appId: '1:1015379365622:android:2036317ba7a8652e1de6d7',
    messagingSenderId: '1015379365622',
    projectId: 'womensafety-79a11',
    storageBucket: 'womensafety-79a11.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAKXj4N3XuhQs0CFK7SX2q3D6uWchJ9E0',
    appId: '1:1015379365622:ios:99858ee74295956b1de6d7',
    messagingSenderId: '1015379365622',
    projectId: 'womensafety-79a11',
    storageBucket: 'womensafety-79a11.firebasestorage.app',
    iosBundleId: 'com.example.womenSafetyApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCAKXj4N3XuhQs0CFK7SX2q3D6uWchJ9E0',
    appId: '1:1015379365622:ios:99858ee74295956b1de6d7',
    messagingSenderId: '1015379365622',
    projectId: 'womensafety-79a11',
    storageBucket: 'womensafety-79a11.firebasestorage.app',
    iosBundleId: 'com.example.womenSafetyApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBku4N55knjPgqlm2Pf20KdM-7AXOizv8o',
    appId: '1:1015379365622:web:148c526291f70cd21de6d7',
    messagingSenderId: '1015379365622',
    projectId: 'womensafety-79a11',
    authDomain: 'womensafety-79a11.firebaseapp.com',
    storageBucket: 'womensafety-79a11.firebasestorage.app',
    measurementId: 'G-ERJ1Q9PC03',
  );

}